# ================================
# Limites de monitoramento
# ================================
CPU_LIMIT=80
MEM_LIMIT=80
DISK_LIMIT=85

# ================================
# Telegram
# ================================
TELEGRAM_BOT_TOKEN="8496488170:AAEOiRPRprh6GZCVcoXA2P-ePgmhh_zekME"
TELEGRAM_CHAT_ID="7500436299"
